"""tables

Revision ID: 9495d5d8bda3
Revises: 
Create Date: 2018-04-12 10:11:17.672423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9495d5d8bda3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=32), nullable=True),
    sa.Column('layout', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_course'), 'course', ['course'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stats', sa.PickleType(), nullable=True),
    sa.Column('course', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('tourney', sa.Boolean(), nullable=True),
    sa.Column('eighteen', sa.Boolean(), nullable=True),
    sa.Column('nine', sa.Boolean(), nullable=True),
    sa.Column('statistics', sa.PickleType(), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.Column('classifier', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_classifier'), 'post', ['classifier'], unique=False)
    op.create_index(op.f('ix_post_course'), 'post', ['course'], unique=False)
    op.create_index(op.f('ix_post_eighteen'), 'post', ['eighteen'], unique=False)
    op.create_index(op.f('ix_post_nine'), 'post', ['nine'], unique=False)
    op.create_index(op.f('ix_post_score'), 'post', ['score'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_post_tourney'), 'post', ['tourney'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_tourney'), table_name='post')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_score'), table_name='post')
    op.drop_index(op.f('ix_post_nine'), table_name='post')
    op.drop_index(op.f('ix_post_eighteen'), table_name='post')
    op.drop_index(op.f('ix_post_course'), table_name='post')
    op.drop_index(op.f('ix_post_classifier'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_course_course'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
